version: '3.3'
services:
  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 'lairpw'
    ports:
      - '3306:3306'
    expose:
      - '3306'
    volumes:
      - ./db/sql:/docker-entrypoint-initdb.d
  api:
    build: .
    depends_on:
      - db
    ports:
      - '80:80'